apiVersion: v1
kind: ConfigMap
metadata:
  name: food-auth-backend-config-map
  namespace: food
data:
  DOMAIN: "http://localhost:3000"
  ALLOWED_ORIGINS: "http://localhost:3001"
  JWKS_URL: "http://localhost:5001/.well-known/jwks.json"
