apiVersion: v1
kind: Secret
metadata:
  name: food-auth-backend-secret
  namespace: food
data:
  DATABASE_HOST: "cXVpemxvb20tZGF0YWJhc2Utc2VydmljZQ=="
  DATABASE_PORT: "NTQzMg=="
  DATABASE_USER: "cm9vdA=="
  DATABASE_PASSWORD: "cm9vdA=="
  DATABASE: "cXVpemxvb20="
  JWT_PRIVATE_KEY_SECRETS: "and0YWNjZXNzdG9rZW5zZWNyZXQ="
  JWT_REFRESH_TOKEN_SECRET: "and0cmVmcmVzaHRva2Vuc2VjcmV0"
  JWT_FORGOT_PASSWORD_TOKEN_SECRET: ZGVtbw==
  SMTP_SERVICE: Z21haWw=
  SMTP_USERNAME: eWFzaGJhbnNvZDIwMjBAZ21haWwuY29t
  SMTP_PASSWORD: ZGVtbw==
