apiVersion: v1
kind: Service
metadata:
  name: food-auth-backend-service
  namespace: food
spec:
  selector:
    app: food-auth-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
