apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: food-auth-database-statefulset
  namespace: food

spec:
  serviceName: food-auth-database-service
  replicas: 2
  selector:
    matchLabels:
      app: food-auth-database
  template:
    metadata:
      labels:
        app: food-auth-database
    spec:
      containers:
        - name: food-auth-database
          image: postgres:17.2
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: food-auth-database-config-map
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: food-auth-database-config-map
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: food-auth-database-config-map
                  key: POSTGRES_DB
          volumeMounts:
            - name: food-auth-database-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: food-auth-database-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
